"""empty message

Revision ID: beb1a5777158
Revises: cea88de4e056
Create Date: 2025-02-24 21:08:48.054500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'beb1a5777158'
down_revision = 'cea88de4e056'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('show', schema=None) as batch_op:
        # 1️⃣ Add 'id' column as nullable
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # 2️⃣ Populate 'id' column with unique values using a sequence
    op.execute("""
        CREATE SEQUENCE show_id_seq OWNED BY show.id;
        UPDATE show SET id = nextval('show_id_seq');
    """)

    # 3️⃣ Set the sequence as the default for 'id', make it NOT NULL, and set it as PRIMARY KEY
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_primary_key('pk_show', ['id'])
        op.execute("ALTER SEQUENCE show_id_seq OWNED BY show.id;")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('show_venue_id_fkey', 'Venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key('show_artist_id_fkey', 'Artist', ['artist_id'], ['id'])
        batch_op.drop_column('id')

    op.create_table('Artist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Artist_pkey')
    )
    op.create_table('Venue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Venue_pkey')
    )
    op.drop_table('venue')
    op.drop_table('artist')
    # ### end Alembic commands ###
